name: Daily Discord Bot Run

on:
  schedule:
    - cron: '0 2 * * *'  # 4h00 du matin en France (Daily Ranking) 🆕
    - cron: '0 4 * * *'  # 6h00 du matin en France (Millie Games)
    - cron: '0 8 * * *'  # 10h00 du matin en France (Eye Contact)
  workflow_dispatch:     # Aligné correctement avec schedule:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install discord.py

      - name: Run Bot Command
        run: python bot.py
