name: Daily Discord Bot Run

on:
  schedule:
    - cron: '0 6 * * *'   # 6h00 UTC = 08h00 pile en France (Millie Games) 🎮
    - cron: '0 12 * * *'  # 12h00 UTC = 14h00 pile en France (Eye Contact) 👀
    - cron: '0 18 * * *'  # 18h00 UTC = 20h00 pile en France (Daily Ranking) 🔟
  workflow_dispatch:     # Aligné correctement avec schedule:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install discord.py

      - name: Run Bot Command
        run: python bot.py
